version: '3.4'

services:
  addons:
    image: addons
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 chie_software/src/sgsi_idu/__init__.py "]
    ports:
      - 5678:5678
